name: Deploy app to demo environment

# start action manually
on: workflow_dispatch

env:
  PATH_TARGET: /home/live/inst/wg/aid-demo
  PRJ: aid-demo
  USER: live
  ZIP: aid-demo.zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repo.
        uses: actions/checkout@v3

      - name: Build application.
        run: |
          ./bin/deploy/live.sh

      - name: Add application files to archive.
        uses: montudor/action-zip@v1
        with:
          args: zip -qq --exclude=*.git* -r ${{env.ZIP}} ./

      - name: Validate archive existence.
        run: ls -lh ${{env.ZIP}}

      - name: Copy files to Remote Server.
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_CONTABO }}
          REMOTE_USER: "${{env.USER}}"
          SOURCE: "${{env.ZIP}}"
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY_CONTABO }}
          TARGET: "${{env.PATH_TARGET}}/../"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT          

      - name: Extract files on Remote Server and switch site to the new instance.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST_CONTABO }}
          username: ${{ env.USER }}
          key: ${{ secrets.SERVER_SSH_KEY_CONTABO }}
          script: |
            cd "${{env.PATH_TARGET}}/../"
            rm -fr ${{env.PRJ}}.old/  
            mkdir ${{env.PRJ}}.new
            unzip ${{env.ZIP}} -d ./${{env.PRJ}}.new/ &> /dev/null
            sudo systemctl stop pwa-${{env.PRJ}}.service
            mv ./${{env.PRJ}} ./${{env.PRJ}}.old
            mv ./${{env.PRJ}}.new ./${{env.PRJ}}
            sudo systemctl start pwa-${{env.PRJ}}.service
            ls -lh ./${{env.PRJ}}/